name: Continuous Integration
on: [push, pull_request]
jobs:
  validate_json:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/validate-json

